name: Build and Deploy
on:
  push:
    branches:
      - main  # replace with your default branch if not "main"
      - deployment-test # remove after testing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # This step checks out a copy of your repository

      - name: Setup Node.js environment 🗳️
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the version of Node.js

      - name: Cache dependencies ⏲️
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies 📦
        run: npm ci

      - name: Build 🏗️
        run: npm run build # This step builds your React application

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
          ssh-key: ${{ secrets.ACTIONS_RUNNER_PUSH_KEY }} # The SSH key that has access to the repository.